engines:
  cppcheck:
    exclude_paths:
      - "src/**/*.h"
      - "src/**/*.cpp"
      - "tests/js/tests/**/*.spec.js"
    rules:
      - missingInclude: false
      - preprocessorErrorDirective: false
    settings:
      suppressions:
        - "missingIncludeSystem:*"